export const callbackCommands = {
  cancelInvoice: 'cancel-invoice',
  cancelTrade: 'cancel-trade',
  moveInvoiceNode: 'switch-invoice-to-',
  moveTradeNode: 'switch-trade-to-',
  removeMessage: 'remove-message',
  setInvoiceDescription: 'set-invoice-description',
  setInvoiceNode: 'set-invoice-node',
  setInvoiceTokens: 'set-invoice-tokens',
  setTradeDescription: 'set-trade-description',
  setTradeExpiresAt: 'set-trade-expires-at',
  setTradeNode: 'set-trade-node',
  terminateBot: 'terminate-bot',
};

export const icons = {
  balanced_open: '⚖️',
  block: '⏹',
  bot: '🤖',
  chain: '⛓',
  closing: '⏳',
  disconnected: '😵',
  earn: '💰',
  forwarding: '💸',
  info: 'ℹ️',
  liquidity: '🌊',
  opening: '⏳',
  probe: '👽',
  rebalance: '☯️',
  receive: '💵',
  spent: '⚡️',
  warning: '⚠️',
};

export const interactions = {
  ask_for_connect_code: 'Run */connect* to authorize.',
  block_notification: '⏹ **New block found**',
  bot: '🤖',
  bot_is_connected: '🤖 *Bot is online.* /help for commands',
  create_invoice_syntax: '/invoice <amount> \\[memo]',
  mempool_report: '⏹ **mempool.space reports:**',
  pay_syntax: '/pay <payment request> \\[max payment amount]',
  payment_is_stuck: '⚠️ Payment is pending',
  peer_not_found: '🤖 Peer not found',
  requesting_block_notification: '🤖 Waiting for next block',
  requesting_mempool: '🤖 Generating mempool report...',
  requesting_mempool_failed: '🤖 Getting mempool from mempool.space failed ☹️',
  select_node_for_invoice: 'Node to make invoice on?',
  select_node_for_payment: 'Node to pay with?',
  start_message: '🤖 *Bot started, run /connect to authorize.*',
};

export const labels = {
  invoiceMessageCancelButtonLabel: '🗑',
  invoiceMessageDescriptionButtonLabel: 'Set Memo',
  invoiceMessageNodeButtonLabel: 'Node...',
  invoiceMessageSetTokensButtonLabel: 'Amount...',
  stopBotCancelButtonLabel: 'Confirm, Stop Bot',
  stopBotConfirmButtonLabel: 'Cancel',
  tradeMessageCancelButtonLabel: '🗑',
  tradeMessageDescriptionButtonLabel: 'Set Description',
  tradeMessageExpiresAtLabel: 'Expiry...',
  tradeMessageNodeButtonLabel: 'Node...',
};
